---
- name: Create BWCE temp directory
  ansible.builtin.file:
    path: '{{ bwce_tmp }}'
    state: directory
    mode: '0755'

- name: Download and unzip BWCE zip archive
  ansible.builtin.unarchive:
      src: '{{ repository.url }}/bwce/{{ tibco.bwce.version }}/linux/{{ bwce_zip }}'
      dest: '{{ bwce_tmp }}'
      remote_src: 'yes'

- name: Instantiate BWCE silent file from template
  ansible.builtin.template:
    src: TIBCOUniversalInstaller_bwce.silent.j2
    dest: "{{ bwce_tmp }}/{{ bwce_silent }}"
    force: 'yes'
    mode: '0755'

- name: Run installer
  ansible.builtin.command:
    cmd: './TIBCOUniversalInstaller-lnx-x86-64.bin -silent -V responseFile={{ bwce_silent }}'
  become: 'yes'
  become_user: "{{ tibco.user.name }}"
  args:
    chdir: "{{ bwce_tmp }}"

- name: Remove BWCE zip archive
  ansible.builtin.file:
    path: '{{ bwce_zip }}'
    state: absent

- name: Remove BWCE temp directory
  ansible.builtin.file:
    path: '{{ bwce_tmp }}'
    state: absent
