---
- name: Download zip file
  get_url:
    url: "{{ repositories.nexus }}/bwce/{{ tibco.bwce.version }}/linux/{{ bwce_zip }}"
    dest: "{{ system.temp }}"

- name: Unzip files
  command: unzip -o {{ bwce_zip }} -d {{ bwce_tmp }}
  args:
    chdir: "{{ system.temp }}"

- name: Instantiate silent file from template
  template:
    src: "TIBCOUniversalInstaller_bwce.silent.j2"
    dest: "{{ bwce_tmp }}/{{ bwce_silent }}"
    force: yes

- name: Run installer
  command: ./TIBCOUniversalInstaller-lnx-x86-64.bin -silent -V responseFile={{ bwce_silent }}
  become: yes
  become_user: "{{ tibco.user.name }}"
  args:
    chdir: "{{ bwce_tmp }}"    

- name: Cleanup
  command: rm {{ bwce_zip }} && rm -rf {{ bwce_tmp }}
  args:
    chdir: "{{ system.temp }}"    