---
- name: Install the latest version of libnsl
  become: 'yes'
  become_user: root
  ansible.builtin.dnf:
    name: libnsl
    state: latest
- name: Install lgpl
  include_tasks: 'lgpl.yml'
- name: Install BWCE
  include_tasks: 'bwce.yml'
- name: Configure Business Studio
  include_tasks: 'studio.yml'
