---
- name: Install the latest version of libnsl
  become: 'yes'
  become_user: root
  ansible.builtin.package:
    name: libnsl
    state: present

- name: Install lgpl
  include_tasks: 'lgpl.yml'

- name: Install BWCE
  include_tasks: 'bwce.yml'

- name: Execute post installation tasks
  include_tasks: 'post-install.yml'
